### ISSUE TITLE
Application web non associable via interface simplifiée

### ISSUE THREAD

**Issue by johannsan** [InfotelGLPI/webapplications#10]
Bonjour.

Via l'interface standard, les applications web sont bien associables au tickets si le profils à accès à tous les éléments du parc.

Par contre, via l'interface simplifiée et pour un profil ne visualisant que "ses élements", il n'y a pas la possibilité d'ajouter des applications web.

Est-ce normal?
En PJ : 
le paramétrage super admin
le paramétrage postonly
la saisie en interface simplifiée et standard
Merci
![profil self service 2](https://cloud.githubusercontent.com/assets/6028912/19559596/de2104f2-96d0-11e6-990d-c81136e5e58f.png)
![avec profil super-admin](https://cloud.githubusercontent.com/assets/6028912/19559595/de207e6a-96d0-11e6-9cbc-5a0ecf885564.png)
![avec post-only](https://cloud.githubusercontent.com/assets/6028912/19559597/de2129f0-96d0-11e6-8ded-52a69f25c22e.png)
![profil self service 1](https://cloud.githubusercontent.com/assets/6028912/19559598/de2f5e1c-96d0-11e6-8be3-f88ab8f5acce.png)

**Comment by tsmr** [comment]
Il faut cocher dans le profil post-only **Tous les éléments** au niveau de Liaison avec les matériels pour la création de tickets

**Comment by johannsan** [comment]
Bonjour.

Le fait de choisir "tous les éléments" est problématique car un utilisateur va pouvoir saisir dans son ticket tous les éléments du parc alors que le but est qu'il saisisse "ses éléments" (son pc, son écran ou ses logiciels inventoriés" ainsi que des "logiciels non inventoriés". C'est pour cela que j'essayai ce plugin.
Mais en effet, si "tous les éléments" sont cochés, ca marche.

Donc ma question est plus large : Comment un utilisateur lambda peut associer "ses éléments" mais aussi des "logiciels ou appli web"  (terme indifférent) non rattachées directement (car pas d'installation sur le poste)?

Merci

**Comment by tsmr** [comment]
Il faudrait qu'il y ai un champ Groupe sur l'application Web, afin d'utiliser la notion de "Voir les matériels de mes groupes.

**Comment by johannsan** [comment]
Oui j'ai bien vu cela, mais un utilisateurs "lambda" qui n'a pas de lien avec ce logiciel particulier ou avec cette application web n'a pas la possibilité de faire un ticket sur cet élement si elle n'a pas acces à l'ensemble du parc?
Ma demande serait bien d'avoir des élements (logiciel ou appications web...) publiques, c'est à dire sans association avec l'utilisateur sur lesquels tout le monde peut faire un ticcet (sans voir l'ensemble du parc)

cdt

**Comment by tsmr** [comment]
Dans glpi le seul moyen de rendre un logiciel **public** est de l'associer à un groupe où tous les utilisateurs sont présents et d'utiliser la notion de **Voir les matériels de mes groupes.**

**Comment by johannsan** [comment]
Merci beaucoup.

**Comment by johannsan** [comment]
Bonjour.
Cette solution fonctionne mais a malheureusement des effets de bord lors de l'utilisation des plannings. Je m'explique.
Nous souhaitons que les utilisateurs puissent voir les planning des personnes de leur groupe. Cela fonctionne correctement, mais malheureusement, si tout le monde est dans ce groupe "public", tout le monde va donc voir tous les planning de tout le monde. Alors que ce groupe "public" n'est qu'un groupe technique et n'a aucune existence réelle ou fonctionnelle.

Cordialement
