### ISSUE TITLE
Contracts dropdown issue

### ISSUE THREAD

**Issue by ventu86** [InfotelGLPI/webapplications#12]
Hi,

- The version of the plugin -
2.2.0
- The version of your GLPI.
9.1.2
- The steps to reproduce your issue.
Create a new Web Application.
Go to the Contracts tab.
The dropdown in the 'Add a contract' remains empty. Only the '-----' item is loaded.
![image](https://cloud.githubusercontent.com/assets/25846766/23069350/626db1f6-f527-11e6-8a9a-91cd25d1d3dc.png)

Thank you.

**Comment by amma35** [comment]
Hello,

Do you have any contracts that are visible in the entity of the web application and which are not related to any element?

**Comment by ventu86** [comment]
Hello,

I have 1 contract related to a Computer entity and 4 other contracts not related.
![image](https://cloud.githubusercontent.com/assets/25846766/23070605/e3310c30-f52b-11e6-8b72-1afd3a08e4d3.png)


But after your reply I have checked the contract and tried to add a new contract and it 
appeared in the dropdown.
![image](https://cloud.githubusercontent.com/assets/25846766/23070653/168dc564-f52c-11e6-8fb3-e91ab230b7ad.png)
![image](https://cloud.githubusercontent.com/assets/25846766/23070671/24ecdbb8-f52c-11e6-87bf-b5a144af6f59.png)

So it seams that the dropdown doesn't load the existing contracts.

**Comment by bacus99** [comment]
simply enable the inheritance in each of your contracts?  No?

**Comment by ventu86** [comment]
How can I do that ?

**Comment by amma35** [comment]
In the contract, it's necessary to put "yes" to Child entities
![image](https://cloud.githubusercontent.com/assets/15138371/23122756/d77f519e-f765-11e6-8e5a-55c5ac928221.png)

**Comment by ventu86** [comment]
Thank you for you explanation.
But unfortunately in my GLPI version there is no Child entities dropdown in the creation of the contract.
![image](https://cloud.githubusercontent.com/assets/25846766/23123533/07f9156e-f769-11e6-8165-68f7379302c1.png)
But I found that using the multiple selection checkbox in the list and then the Action button it is possible to update the parameter that you mentioned. So, this is eventually an acceptable solution.
![image](https://cloud.githubusercontent.com/assets/25846766/23123665/8dd301ae-f769-11e6-8bff-d76d675d8146.png)
![image](https://cloud.githubusercontent.com/assets/25846766/23123706/cd527062-f769-11e6-85b5-39a267dfec6c.png)
But the change doesn't affect the Contract dropdown in the Web Application tab. Only the first contract, that I had created after installing your plugin, is visible.
![image](https://cloud.githubusercontent.com/assets/25846766/23123762/0d900874-f76a-11e6-9a0f-bdc6473a1079.png)

The version of GLPI is in the initial post as required.
Your screen seems to have a different graphics, maybe it is only the GLPI web theme.

**Comment by amma35** [comment]
The versions that you indicated in the first post are good?
```
The version of the plugin - 2.2.0
The version of your GLPI - 9.1.2
```

Because no release has been out for version 2.2.0 plugin ...

**Comment by amma35** [comment]
Is it good for you ?
In this list the end date of the contract is taken into account so if it is less than the date of the day, the contract will not be visible.

**Comment by amma35** [comment]
I close your request without any news from you, however if the problem persists open a new issue.

In addition, a new release is released.
