### ISSUE TITLE
webapplicationtypes is not recursive to entities

### ISSUE THREAD

**Issue by bla-kw** [InfotelGLPI/webapplications#19]
* Version of the plugin :
2.5.1

* Version of your GLPI :
9.3.1

* Steps to reproduce (which actions have you made) :
Create a webapplicationtype in Root entity. Go to a sub entitiy, create a webapplication and you do not see the webapplicationtype from the Root entity. The webapplicationservertype and webapplicationtechnics are available in the sub entity.

* Expected result :
I would expect to see the webapplicationtype from the root entity like the webapplicationservertype or webapplicationtechnics. Or I am expecting to have a checkbox when editing a webapplicationtype to set it recursive.

* Actual result :
I don't see the webapplicationtype from root entity and I see no checkbox to enable recursive behaviour.

I don't have much experience with GLPI yet, but when I compare the webapplicationtypes table with others, where it is working there seems to be missing a column "is_recursive".
I have tried to add this column with:
`ALTER TABLE glpi_plugin_webapplications_webapplicationtypes ADD is_recursive TINYINT(1) DEFAULT '1';`
and it seems to work now as expected.

**Comment by keha35** [comment]
Hello,

Thank for the feedback!
It will be implemented in the next release.
