### ISSUE TITLE
Link with certificate

### ISSUE THREAD

**Issue by redfish0** [InfotelGLPI/webapplications#21]
* Version of the plugin : 2.4.1
* Version of your GLPI : 9.2.3

Hello,
Wouldn't it make sense for a web application to be associated with certificates ?

I did not find how if it is already feasible....

Thank you

Patrick

**Comment by redfish0** [comment]
Hello,
Strange I do not have this option neither directly in "Action" nor when I choose "Associate"....

![2018-11-12 11_07_11-glpi - applications web - internet explorer](https://user-images.githubusercontent.com/939519/48340794-cbce8a80-e66b-11e8-9a81-cf591093ac68.png)

**Comment by keha35** [comment]
Indeed,

It was because i haven't desable my old plugin certificates.
You can apply this commit : 
https://github.com/InfotelGLPI/webapplications/commit/25fe3c17b4b8d55d321e3b7c1106081a9eeb47c2

**Comment by redfish0** [comment]
OK it's working with your patch, however my webapplication.class.php did not have the 'PluginWebapplicationsWebapplication' part at line 44. I did not add that one as 'Certificate' was enough to fix the issue.

Thank you

Patrick
