### ISSUE TITLE
Evo : Lien avec les projets Utilisateurs Groupes ?

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/webapplications#23]
Bonjour

Serait-il possible de lier les web-applications avec les Projets en tant qu'elements attachés?
Ainsi il serait possible de suivre la vie d'une application web, fonction des demandes de projets...

D'autre part, toujours dans les elements attachés : pourquoi ne pas ajouter la notion de groupe et d'utilisateurs ?

En effet, le responsable technique et le groupe technique sont les seuls disponibilités pour ajouter des contacts pour une application web...

D'avance merci

**Comment by EC2311** [comment]
Bonjour,

Ajouter dans inc\webapplication.class.php 
   static $types = ['Computer', 'Monitor', 'NetworkEquipment', 'Peripheral', 'Phone',
                         'Printer', 'Software', 'Entity', 'SoftwareLicense', 'PluginWebapplicationsWebapplication',**'Project','Group','User'**];

**Comment by tsmr** [comment]
Complete review of this plugin
I close
