### ISSUE TITLE
EVO : Nouveau Champs

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/webapplications#26]
Bonjour

Serait-il possibel d'ajouter un nouveau champs : Status, qui permettrait d'ajouter une information d'évolution, migration ou toute autre information ?

D'avance merci

**Comment by EC2311** [comment]
Bonjour
De la meme manière, un champ "propriétaire" du site, basé peut etre sur la notion de "groupe" ?
Merci

**Comment by tsmr** [comment]
Complete review of this plugin
I close
