### ISSUE TITLE
Fatal Error : Datainjection with web-applications

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/webapplications#28]
Hello

when linking to the fields of web-applications : fatal error (same for the 2 versions)

GLPI : 9.3.1
Plugin datainjection 2.6.4
Plugin web-applications 2.5.0

Fatal error: Uncaught TypeError: Argument 3 passed to PluginDatainjectionCommonInjectionLib::addToSearchOptions() must be an instance of PluginDatainjectionInjectionInterface, instance of PluginWebapplicationsWebapplicationInjection given, called in wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php on line 89 and defined in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php:1967 Stack trace: #(0 wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php(89): PluginDatainjectionCommonInjectionLib::addToSearchOptions(Array, Array, Object(PluginWebapplicationsWebapplicationInjection)) #(1 wwwroot\plugins\datainjection\inc\injectiontype.class.php(204): PluginWebapplicationsWebapplicationInjection->getOptions('PluginWebapplic...') #(2 wwwroot\plugins\datainjection\ajax\dropdownChooseField.php(39): Plu in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php on line 1967

GLPI : 9.4.3
Plugin datainjection: 2.7.0
Plugin web-applications : 2.6.0

Fatal error: Uncaught TypeError: Argument 3 passed to PluginDatainjectionCommonInjectionLib::addToSearchOptions() must be an instance of PluginDatainjectionInjectionInterface, instance of PluginWebapplicationsWebapplicationInjection given, called in wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php on line 89 and defined in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php:1967 Stack trace: #(0 wwwroot\plugins\webapplications\inc\webapplicationinjection.class.php(89): PluginDatainjectionCommonInjectionLib::addToSearchOptions(Array, Array, Object(PluginWebapplicationsWebapplicationInjection)) #(1 wwwroot\plugins\datainjection\inc\injectiontype.class.php(204): PluginWebapplicationsWebapplicationInjection->getOptions('PluginWebapplic...') #(2 wwwroot\plugins\datainjection\ajax\dropdownChoo in wwwroot\plugins\datainjection\inc\commoninjectionlib.class.php on line 1967

Bug opened in datainjection and transfered here.

Best regards

**Comment by EC2311** [comment]
Hello

No update on this error ?
Thanks
Best regards

**Comment by tsmr** [comment]
Complete review of this plugin
I close
