### ISSUE TITLE
Plugin is "deleted" when cron is executed 

### ISSUE THREAD

**Issue by rcfloresh** [InfotelGLPI/webapplications#29]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
2.6.0

* Version of your GLPI : 
9.4.6

* Steps to reproduce (which actions have you made) :
1. Download the plugin
2. Unzip the plugin
3. Move the plugin to plugins folder
4. Go to GLPI plugins section 
5. Install webapplication plugins
6. Enable webapplication plugins
7. Wait the cron execution (1 minute)
8. The plugin was "deleted", because the clear icon it's showing it. 
9. Click on clean
10. The option to install appear again. 
11. Steps 5 to 10 reproduce again 

* Expected result :
That the plugin won't be deleted or reinstall each minute

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
Complete review of this plugin
I close
