### ISSUE TITLE
plugin and ticket list interaction issue

### ISSUE THREAD

**Issue by Stoatwblr** [InfotelGLPI/webapplications#34]
* Version of the plugin : 

3.0.0

* Version of your GLPI : 

9.5.1, 9.5.2

* Steps to reproduce (which actions have you made) :

 install plugin, activate
drop to selfservice mode, then move back to superadmin

* Expected result :

plugins list should be visible

* Actual result 

plugins are only visible via the marketplace, users in selfservice mode cannot see their tickets

Disabling the plugin restores normal operation

**Comment by tsmr** [comment]
Complete review of this plugin
I close
