### ISSUE TITLE
GLPI 9.5.1 plug-in Web applications not work "Core migration" screen

### ISSUE THREAD

**Issue by Dusitswat** [InfotelGLPI/webapplications#35]
![err-web](https://user-images.githubusercontent.com/72538916/95416268-7fc21880-095c-11eb-8258-7a62dda45548.JPG)

Web applications not work 9.5 "Core migration" screen

**Comment by gguib** [comment]
Hi, 

it still does not work ? Please do refresh and retry you must see a pop-up that gives you last warning ?
Some browser js log ?

**Comment by Dusitswat** [comment]
![image](https://user-images.githubusercontent.com/72538916/98092591-66f44680-1eb9-11eb-8e85-3b6888e650e0.png)
Click --> Confirm and refresh --> Next screen is
![image](https://user-images.githubusercontent.com/72538916/98093248-44aef880-1eba-11eb-94ca-7c8b2de5dc89.png)

**Comment by gguib** [comment]
Hi,

Have you check your profile rights first ?

**Comment by Dusitswat** [comment]
super-admin
![image](https://user-images.githubusercontent.com/72538916/98095625-66f64580-1ebd-11eb-9483-c63291725636.png)

**Comment by gguib** [comment]
You must have session issues or cache maybe ? because if you check #36 issue. migration was able to be launch for others users.
