### ISSUE TITLE
Core Migration doesn't migrate all tables to Appliances, or delete some of them.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/webapplications#36]
Hi, I'm getting some errors on the new version plugin 3.0.0 for GLPI 9.5.2 when opening an already Appliances.

Comparing my 2 DBs, the original GLPI 9.4.6 Plugin 2.6.0 and the clone upgraded to GLPI 9.5.2 Plugin 3.0.0 and applied Core migration, I notice one table dissapear and another ones don't migrate the data, like:

- glpi_plugin_webapplications_webapplicationtechnics -> Dissapear
- glpi_plugin_webapplications_webapplications_items -> glpi_appliances_items
- glpi_plugin_webapplications_webapplicationtypes -> glpi_appliancetypes
-glpi_plugin_webapplications_webapplicationservertypes

- GLPI 9.4.6 Plugin 2.6.0

```
select count(*) from glpi_plugin_webapplications_webapplicationtechnics;
+----------+
| count(*) |
+----------+
|        6 |
+----------+

select count(*) from glpi_plugin_webapplications_webapplications_items;
+----------+
| count(*) |
+----------+
|       10 |
+----------+

select count(*) from glpi_plugin_webapplications_webapplicationtypes;
+----------+
| count(*) |
+----------+
|        4 |
+----------+

select count(*) from glpi_plugin_webapplications_webapplicationservertypes;
+----------+
| count(*) |
+----------+
|        4 |
+----------+
```

- VS. GLPI 9.5.2 Plugin 3.0.0 and applied Core migration

```
select count(*) from glpi_appliances_items;
+----------+
| count(*) |
+----------+
|        0 |
+----------+

select count(*) from glpi_appliancetypes;
+----------+
| count(*) |
+----------+
|        0 |
+----------+

select count(*) from glpi_plugin_webapplications_webapplicationservertypes;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
```

It's problem repercute to another's plugins like Environment, Accounts, Database.

------------
* Version of the plugin : 
3.0.0

* Version of your GLPI : 
9.5.2

* Steps to reproduce (which actions have you made) :

1. Go to Setup
2. Click on Plugins
3. Click on Web Application Configure
4. Click on Core migration
5. See tables on database doesn't migrate all data.

Also:

1. Once Core Migration, Go to Management
2. Click on Appliances
3. Click on an Item
4. Click on Appliance
5. See error on Category and Language of treatment

* Expected result :
All the data had migrated correctly and Category and Language of treatment return the correct data.

* Actual result :
- Category:

> SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplicationtypes' doesn't exist in query "SELECT `glpi_plugin_webapplications_webapplicationtypes`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_plugin_webapplications_webapplicationtypes` WHERE `glpi_plugin_webapplications_webapplicationtypes`.`id` = '3'"
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplicationtypes' doesn't exist in query "SELECT * FROM `glpi_plugin_webapplications_webapplicationtypes` WHERE `glpi_plugin_webapplications_webapplicationtypes`.`id` = '3' LIMIT 1"
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplicationtypes' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_webapplications_webapplicationtypes`"

- Language of treatment:

> SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplicationtechnics' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_webapplications_webapplicationtechnics`"

* URL of the page :
/appliance.form.php
/plugins/webapplications/front/webapplication.php

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/56606032/96768902-fec74000-13a3-11eb-8cdc-358aeb46bf6b.png)

**Comment by gguib** [comment]
Hi, 

I add migration on glpi_plugin_webapplications_webapplicationtypes -> glpi_appliancetypes. Please check new version

We removed glpi_plugin_webapplications_webapplications_items, so there's no migration.

I update Glpi 9.4 to 9.5 and webapplication 2.3.0 to 3.0.0 glpi_plugin_webapplications_webapplicationtechnics and my webapplicationtechnics migration works, same for servertypes (there's no action on it on migration, so he must keeps all from the last version). 

unfortunately, i don't have errors on appliance form related to your sql errors. it still does not work?

**Comment by gguib** [comment]
Hi, 

Please check new commit on master branch.

**Comment by jcervantes-sipecom** [comment]
Hi, Ok I will try.
