### ISSUE TITLE
Core Migration 3.0.0 -> Probleme Migration

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/webapplications#37]
Bonjour

Comme les precedents tickets ont ete cloturés, j'ouvre un nouveau.

- Les types d'applications de la table 'glpi_plugin_webapplications_webapplicationtypes' ne sont pas migrés dans 'glpi_appliancetypes'

- Les elements attachés 'ordinateurs', 'structure d'appli' (autre plugin), projet (elements attachés) liés au plugin web ne sont pas recopiés 'glpi_appliances_items' avec les types respectifs...

Ou sont passées les notions de fournisseur, version ?

Le champ 'type applicatif' ne peut pas être ajouté sur l'ecran principal...

Il serait bien de pouvoir ajouter l'element 'type projet' à l'applicatif.

**Comment by C-Duv** [comment]
J'ai rencontré le même problème lors d'une migration de GLPI :

* Versions GLPI : de v9.4.6 à v9.5.11
* Versions plugin : de v2.6.0 à v3.0.0

Les liens visibles dans les onglets suivants n'ont pas été importés/migrés :

* Éléments (ordinateurs, certificats, …)
* Tickets
* Documents
* Contrats

Existe-t-il un script à exécuter manuellement pour importer ces données ?

**Comment by C-Duv** [comment]
[J'ai pondu](https://github.com/glpi-project/glpi/pull/13408) une variante de la commande `appliances_plugin_to_core` existante mais pour le plugin _webapplications_.

A voir si ça convient aux développeurs·ses de GLPI et/ou aux développeurs·ses de ce plugin.

En tout cas, pour ma migration de 9.4 à 9.5.11 ça semble faire le taff.

**Comment by C-Duv** [comment]
Vu que les mises à jour de GLPI v9.5 ne peuvent que se limiter aux mises à jour de sécurité, [ma PR](https://github.com/glpi-project/glpi/pull/13408) n'a pas été acceptée, il faudrait que je la refasse pour GLPI v10 avec une nouvelle base moderne de gestion des migrations.

Dans l'intervalle je propose ici une PR (#41) pour modifier le script existant de migration de la version v3.0.0.

**Comment by tsmr** [comment]
Complete review of this plugin
I close
