### ISSUE TITLE
Problema no Core Migration

### ISSUE THREAD

**Issue by carlosbayerl** [InfotelGLPI/webapplications#38]
Olá

Como os tickets anteriores foram fechados, abro um novo.

Os tipos de aplicativos da tabela 'glpi_plugin_webapplications_webapplicationtypes' não são migrados para 'glpi_appliancetypes'

Os elementos anexados 'computadores', 'estrutura do aplicativo' (outro plug-in), projeto (elementos anexados) vinculados ao plug-in da web não são copiados 'glpi_appliances_items' com os respectivos tipos ...

Onde estão as noções de fornecedor, versão?

O campo 'tipo de aplicativo' não pode ser adicionado na tela principal ...

Seria bom poder adicionar o elemento 'tipo de projeto' ao aplicativo.

**Comment by tsmr** [comment]
Complete review of this plugin
I close
