### ISSUE TITLE
API access?

### ISSUE THREAD

**Issue by avelor** [InfotelGLPI/webapplications#42]
Hello!

Is it possible to get (and set) fields values through api?
I try to get some info via [glpiurl]/apirest.php/PluginWebapplicationsAppliance and got an error "ERROR_RIGHT_MISSING" (we use plugin with appliences).
Rights and profile is super-admin, but i'm not shure that I make api call to right uri or possible it is or not..
will be glad at any advice!

------------
* Version of the plugin :  4.0.1

* Version of your GLPI :  10.0.6

**Comment by tsmr** [comment]
Complete review of this plugin
I close
