### ISSUE TITLE
Changes not a menu option in Web Application

### ISSUE THREAD

**Issue by tyronewyatt** [InfotelGLPI/webapplications#5]
When viewing a Web application It would be nice to list the Changes like how Tickets and Problems are shown. 

See how Changes is listed in software but not in Web Applications.

![gpi0 90 2-items-software](https://cloud.githubusercontent.com/assets/13756677/14301689/396cf26a-fbdd-11e5-925a-56af5555f3a8.GIF)

![gpi0 90 2-items-webapplication](https://cloud.githubusercontent.com/assets/13756677/14301688/3969a0ec-fbdd-11e5-8041-dabd036c03b9.GIF)

**Comment by ychoucha** [comment]
same problems, i can't found the plugin, in all mene of GLPI, 
i do an upgrade from 0.8 to 0.9
