### ISSUE TITLE
Web Application not associating with ticket 

### ISSUE THREAD

**Issue by grego1981** [InfotelGLPI/webapplications#6]
Hello,
I have version 0.90.1 of glpi with version 2.1.1 of web applications. I have made a web app made it associable to ticket and connected a computer to the app as well as the entity which does not appear in the connected items list.. When creating a ticket the web app is not selectable. How can assign the web app so as to be selectable?

Thank you and best regards
Gregory

**Comment by satyan01** [comment]
same behavior on 9.2 for me

**Comment by amma35** [comment]
In the "Assistance" tab of the profile, "Web application" has been added to the list "Associable items to a ticket"?

![image](https://cloud.githubusercontent.com/assets/15138371/22022365/f3969f9a-dcc1-11e6-83c1-14a8646dac81.png)

You can test in the web application, if you create a ticket for this item, does it work?

![image](https://cloud.githubusercontent.com/assets/15138371/22022395/23142814-dcc2-11e6-9d03-761bd68cdfc1.png)

**Comment by Nicos258** [comment]
hi,
i have the version 0.90.3 with version 2.1.1 of web applications.
I selected into PROFIL : Super-admin "application web" for add with a ticket.

But when i create an ticket (with super-admin), i didn't see "Application web" into the list. Only  computer, screen, phone, ...

Should it be manipulated in another place?
Thanks for your help
Nicos

**Comment by amma35** [comment]
I can not reproduce your bug.
However, in order for "Web applications" to be visible in the tickets, I had to restart the session.

**Comment by amma35** [comment]
I close your request without any news from you, however if the problem persists open a new issue.

In addition, a new release is released.
